feat: optimise webpack config.
Old way spawned multiple node instances. We cant do this anymore.

fixed:
ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.

fixed:
Conflict: Multiple chunks emit assets to the same filename